task5
abhin2002/prapro pull request #2
Opened 2024-02-13 10:06 UTC by abhin2002

2024-02-13 15:19 UTC, FayazRahman requested changes

2024-02-13 15:19 UTC, FayazRahman commented on task_5/task5.py
> +        self.df = pd.read_parquet(pq_file)
Don't read full file, specify `columns` to save memory and time

2024-02-14 01:32 UTC, abhinpt0 commented on task_5/task5.py
> +        self.df = pd.read_parquet(pq_file)
Done 👍

2024-02-14 07:11 UTC, FayazRahman requested changes

2024-02-14 07:11 UTC, FayazRahman commented on task_4/task4.py
> +        with open(f'images/image_{i}.jpg', 'wb') as f:
All files may not be `.jpg`

2024-02-14 07:11 UTC, FayazRahman commented on task_4/task4.py
> +table = pq.read_table('links.parquet')
Read required columns only.

2024-02-14 07:11 UTC, FayazRahman commented on task_5/task5.py
> +            local_path = self.base_path + f'image_{key}.jpg'
All paths may not be `.jpg`

2024-02-15 02:42 UTC, abhin2002 commented on task_4/task4.py
> +table = pq.read_table('links.parquet')
done

2024-02-15 15:24 UTC, abhin2002 commented on task_4/task4.py
> +        with open(f'images/image_{i}.jpg', 'wb') as f:
updated

2024-02-15 16:02 UTC, FayazRahman approved these changes

2024-02-15 16:07 UTC, merged